### ISSUE TITLE
can't install client lib

### ISSUE THREAD

**Issue by wangfan860** [anvilproject/client-apis#10]
hello, thank you for making this package. I can't wait to give it a try. However, I can't run `pip install -e .` and got this error: ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:

And when I run `python  pyAnVIL/anvil/cli.py`, i got `AttributeError: module 'anvil' has no attribute 'get_projects'`

**Comment by bwalsh** [comment]
I just saw this now.  :-(
I'll investigate and get back ASAP
