### ISSUE TITLE
Indicate which data are public on Data Dashboard

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/client-apis#12]
Indicate on the Data Dashboard which cohorts/groups of data are "public". 

This could just represent the access levels associated with each group/workspace, whether they are:
- open, unrestricted (1000 Genomes)
- open, restricted (GTEx)
- available to consortia only, restricted (CCDG, CMG)

We should confirm with Andrew at Broad about the access levels associated with each group/workspace.

**Comment by MoHeydarian** [comment]
Ping @andrewrula for insight, can we use the auth domain associated with workspaces to indicate access controls for each group/cohort of datasets?

**Comment by bwalsh** [comment]
implemented
